# Generated by Django 4.1.5 on 2023-02-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkımda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=20)),
                ('icerik', models.TextField()),
                ('image', models.ImageField(upload_to='hakkımda')),
            ],
        ),
        migrations.CreateModel(
            name='Hizmetler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=50)),
                ('icerik', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
