# Generated by Django 4.1.5 on 2023-02-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atakumbungalov', '0002_galeri_alter_hakkımda_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anasayfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='galeri')),
            ],
            options={
                'verbose_name': 'Anasayfa Foto',
            },
        ),
    ]
