# Generated by Django 4.1.5 on 2023-02-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atakumbungalov', '0004_iletisimform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anasayfa',
        ),
        migrations.DeleteModel(
            name='iletisimForm',
        ),
        migrations.AddField(
            model_name='galeri',
            name='anasayfa_active',
            field=models.BooleanField(default='False'),
        ),
    ]
