# Generated by Django 4.1.5 on 2023-02-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atakumbungalov', '0005_delete_anasayfa_delete_iletisimform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnasayfaHizmetler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=50, verbose_name='Başlık')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(upload_to='', verbose_name='Resim')),
            ],
        ),
    ]
