# Generated by Django 4.1.5 on 2023-02-07 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atakumbungalov', '0006_anasayfahizmetler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anasayfahizmetler',
            options={'verbose_name': 'Ana Sayfa Hizmetler', 'verbose_name_plural': 'Ana Sayfa Hizmetler'},
        ),
        migrations.AlterModelOptions(
            name='galeri',
            options={'verbose_name': 'Galeri', 'verbose_name_plural': 'Galeri'},
        ),
        migrations.AlterModelOptions(
            name='hakkımda',
            options={'verbose_name': 'Hakkımda', 'verbose_name_plural': 'Hakkımda'},
        ),
        migrations.AlterModelOptions(
            name='hizmetler',
            options={'verbose_name': 'Hizmetler', 'verbose_name_plural': 'Hizmetler'},
        ),
        migrations.AddField(
            model_name='galeri',
            name='yayıntarih',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yayın Tarihi'),
            preserve_default=False,
        ),
    ]
