# Generated by Django 4.1.5 on 2023-02-07 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_ad_soyad_contact_adsoyad'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
