# Generated by Django 4.1.5 on 2023-02-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_tarih'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='MESAJ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, verbose_name='TARİH'),
        ),
    ]
